apiVersion: v1
data:
  default.conf: |-
    server {
        listen 80 default_server;
        server_name _;
        default_type text/plain;

        location / {
            return 200 '$hostname\n version ! 1 ! \n';
        }
    }
kind: ConfigMap
metadata:
  namespace: k8s-canary
  name: nginx-configmap-v1
